name: Front-End

on:
  [push, pull_request]:
    branches:
      - master
      - develop

env:
  java_version: '14.x'
  flutter_version: '1.22.3'

jobs:
  flutter_test:

    name: Test Flutter on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
            gradle_path: |
              ~/.gradle/caches
              ~/.gradle/wrapper

    defaults:
      run:
        shell: bash
        working-directory: app/manage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Java/Gradle
        uses: actions/cache@v2
        with:
          path: ${{ matrix.gradle_path }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}-${{ hashFiles('**/pubspec.*') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ env.flutter_version }}-
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: List versions
        run: |
          java --version
          flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Start tests
        run: flutter test

  flutter_build:

    name: Build Flutter on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
            gradle_path: |
              ~/.gradle/caches
              ~/.gradle/wrapper

    defaults:
      run:
        shell: bash
        working-directory: app/manage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Java/Gradle
        uses: actions/cache@v2
        with:
          path: ${{ matrix.gradle_path }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}-${{ hashFiles('**/pubspec.*') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ env.flutter_version }}-
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: List versions
        run: |
          java --version
          flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
